Algoritmo "Circulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : jailson
// Descrição   : Calculando a area de um circulo
// Autor(a)    : kevyn
// Data atual  : 20/03/2024
Var
// Seção de Declarações das variáveis
area,raio:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Digite um valor do raio de um circulo:")
leia(raio)
area<-raio*raio*pi
Escreval("o valor da area do raio de um circulo é:",area)
Fimalgoritmo